### ISSUE TITLE
Definir paleta de cores

### ISSUE THREAD

**Issue by xulispa** [TallerWebSolutions/drupal-de-elite#6]
Estudo de conjunto de cores de acordo a identidade do Drupal de Elite.

**Comment by lhguerra** [comment]
https://magic.piktochart.com/editor/piktochart/5312475

Username: tallerws
Pass: socialtaller123

**Priorizar cores escuras para o fundo.

Ambiente dev:
http://dev-drupal-de-elite.dropit.in/
