### ISSUE TITLE
Alterar o cabeçalho

### ISSUE THREAD

**Issue by xulispa** [TallerWebSolutions/drupal-de-elite#8]
- xx Retirar slogan
- xx footer*\* Mover barra social para lateral
- xx Aplicar largura infinita
- Criar novo estilo de menu
  - xx Retirar o menu de eventos

**Comment by xulispa** [comment]
Obs: Enviar modelos de cabeçalhos pra Liz

**Comment by lhguerra** [comment]
Barra social movida para o footer.

**Comment by lhguerra** [comment]
https://files.slack.com/files-pri/T0268UAM6-F04HJ9EU1/imagem18.png

https://files.slack.com/files-pri/T0268UAM6-F04HG3FUQ/guia-de-estilo-de-p1-01-01.png

**Comment by lhguerra** [comment]
https://files.slack.com/files-pri/T0268UAM6-F04L3KVK1/especificacoes-header-01.png

**Comment by lhguerra** [comment]
easysocial deve aparecer apenas em corpo de conteúdo nas páginas internas
